/**
 * Wsl command: windows subsystem linux
 * 
 * wsl --install
 * 
 * wsl --install --distribution <Distribution name>
 * 
 * List installed Linux distributions:
 * wsl --list --verbose
 * 
 * Set WSL version to 1 or 2:
 * wsl --set-version <distribution name> <versionNumber>
 * 
 * set default version:
 * wsl --set-default-version <Version>
 * 
 * update wsl:
 * wsl --update
 *  
 * uname -a
 * 
 * lsb_release -a
 * 
 * COMMANDS:
 *    identify  - WS-Identify
 *    enum      - WS-Enumerate
 *    get       - WS-Get
 *    put       - WS-Put
 *    invoke    - WS-Invoke
 *    xclean    - Delete all files generated by this tool set
 *    xcred     - Create or display credential file
 *    xcert     - Get server certificate (saved to <IPADDRESS>.crt)
 */